# Configurações da Aplicação Spring Boot

# Porta do servidor
server.port=8181
server.servlet.context-path=/

# Logging
logging.level.root=INFO
logging.level.core=DEBUG
logging.level.infrastructure=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Desabilitar banner (opcional)
spring.main.banner-mode=off

# UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Threads virtuais (Java 21+)
spring.threads.virtual.enabled=true

# Jackson (JSON)
spring.jackson.serialization.indent-output=true
spring.jackson.default-property-inclusion=non_null

# Tomcat
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
